server:
  port: 8083

spring:
  application:
    name: ms-ordenes

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:h2:mem:ordenesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true